<?php

/**
 * @file
 * Provides a pantheon content publisher entity type.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\pantheon_content_publisher\ProgressBar;
use Drupal\search_api\Plugin\views\field\SearchApiEntityField;

/**
 * Implements hook_theme().
 */
function pantheon_content_publisher_theme(): array {
  return [
    'pantheon_document' => ['render element' => 'elements'],
    'pantheon_smart_instance' => ['render element' => 'elements'],
    'pantheon_progress' => [
      'variables' => [
        'items' => [],
        'current_step' => 0,
      ],
    ],
  ];
}

/**
 * Prepares variables for pantheon content publisher templates.
 *
 * Default template: pantheon-content-publisher.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the pantheon content publisher
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_pantheon_document(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for pantheon content publisher templates.
 *
 * Default template: pantheon-content-publisher.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the pantheon content publisher information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_pantheon_smart_instance(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

function template_preprocess_pantheon_progress(array &$variables): void {
  $variables['#attached']['library'][] = 'pantheon_content_publisher/progress';
}

/**
 * Implements hook_entity_operation_alter().
 */
function pantheon_content_publisher_entity_operation_alter(array &$operations, EntityInterface $entity) {
  $entityTypeId = $entity->getEntityTypeId();
  if ($entityTypeId === 'pantheon_smart_component') {
    unset($operations['manage-form-display']);
  }
  if ($entityTypeId === 'pantheon_document_collection') {
    unset($operations['manage-fields'], $operations['manage-form-display']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pantheon_content_publisher_form_search_api_server_form_alter(&$form) {
  ProgressBar::addProgressBar($form, ProgressBar::SERVER);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pantheon_content_publisher_form_key_add_form_alter(&$form) {
  if (\Drupal::request()->query->get('key_type') === 'pantheon_content_publisher') {
    ProgressBar::addProgressBar($form, ProgressBar::KEY);
    $form['settings']['type_section'] = [];
    $form['settings']['type_section']['key_type'] = [
      '#type' => 'value',
      '#value' => 'pantheon_content_publisher',
    ];
    $form['label']['#title'] = t('Access token name');
    $form['settings']['input_section']['key_input_settings']['key_value']['#title'] = t('Access token value');
    $form['description']['#description'] = t('A short description of the access token.');
    $form['settings']['provider_section']['read_more'] = [
      '#markup' => '<p>' . t('Find more about providers <a href="https://www.drupal.org/docs/contributed-modules/key/concepts-and-terminology#s-key-providers">here</a>, find a list of available providers <a href="https://www.drupal.org/docs/contributed-modules/key/supported-modules#s-providers-modules">here</a>.') . '</p>',
    ];
    $form['#title'] = 'Add access token';
  }
}

/**
 * Implements hook_element_info_alter().
 */
function pantheon_content_publisher_element_info_alter(array &$info) {
  unset($info['key_select']['#empty_option']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pantheon_content_publisher_form_views_ui_config_item_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $handler = $form_state->get('handler');
  if ($handler instanceof SearchApiEntityField && $handler->realField === 'entity:pantheon_document/content') {
    $form['options']['field_rendering']['#disabled'] = TRUE;
    $form['options']['field_rendering']['#value'] = 1;
    $form['options']['type']['#options'] = array_intersect_key($form['options']['type']['#options'], ['pantheon_document_tags_formatter' => TRUE]);
  }

}
