pantheon_content_publisher.pantheon_document_collection.*:
  type: config_entity
  label: Pantheon content publisher collection
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: required_label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    site_id:
      type: string
      label: 'Site id'
    token:
      type: string
      label: Token
    url:
      type: string
      label: 'Site Url'
    search_api_server:
      type: string
      label: 'Search API server'
field.storage.pantheon_document.*:
  type: field.storage.*.*
field.storage.pantheon_document.*.third_party.pantheon_content_publisher:
  type: mapping
  mapping:
    pantheon_data:
      type: sequence
      label: The data as received from Pantheon
      sequence:
        type: ignore

pantheon_content_publisher.pantheon_smart_component.*:
  type: config_entity
  label: Pantheon smart component
  mapping:
    id:
      type: string
      label: ID
    title:
      type: label
      label: title
    uuid:
      type: string
    icon:
      type: integer
      label: 'Icon'

plugin.plugin_configuration.search_api_processor.pantheon_tags:
  type: search_api.fields_processor_configuration
  label: 'Pantheon tags processor configuration'
