<?php

declare(strict_types=1);

namespace Drupal\Tests\pantheon_content_publisher\Kernel;

use Drupal\Component\Utility\NestedArray;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\KernelTests\KernelTestBase;
use Drupal\pantheon_content_publisher\Controller\PantheonContentPublisherController;
use Drupal\pantheon_content_publisher\PantheonContentPublisherCollInterface;
use Drupal\pantheon_content_publisher\PantheonContentPublisherStorage;
use Drupal\search_api\Entity\Index;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Response;
use Symfony\Component\HttpFoundation\Request;

/**
 * Test description.
 *
 * @group pantheon_content_publisher
 */
class PantheonContentPublisherTest extends KernelTestBase {

  const ARTICLE_ID = '1_dRWJT4gJ05ZwtD6HyE1GdRxExL4FIAMkDIcIH8nlgM';

  /**
   * The key is a method name, the value is a GraphQL query string template.
   *
   * Most methods store the query generated by the same named method on the
   * GraphQL class except for getPage2ArticleIds which stores the call to
   * getArticleIds asking for the second page.
   *
   *  %s in the template stands for site id or article id, depending on the
   *  query type stored in ::QUERY_TYPES.
   */
  const QUERIES = [
    'metadata' => '{site(id:"%s"){metadataFields}}',
    'getArticle' => '{article(id:"%s"){title,content,metadata}}',
    'getArticles' => '{articlesv3{articles{id,title,metadata}}}',
    'getArticleIds' => '{articlesv3(pageSize:100){articles{id},pageInfo{nextCursor}}}',
    'getPage2ArticleIds' => '{articlesv3(pageSize:100,cursor:"next cursor"){articles{id},pageInfo{nextCursor}}}',
  ];

  /**
   * The query type, defaults to articlesv3.
   */
  const QUERY_TYPES = [
    'metadata' => 'site',
    'getArticle' => 'article',
  ];

  /**
   * Guzzle responses keyed by GraphQL queries.
   *
   * @var array
   */
  protected array $storage = [];

  protected PantheonContentPublisherCollInterface $collection;

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'system',
    'media',
    'file',
    'image',
    'field',
    'options',
    'text',
    'pantheon_content_publisher',
    'pantheon_content_publisher_test',
    'search_api',
    'search_api_db',
    'search_api_db_defaults',
    'user',
  ];

  protected function setUp(): void {
    parent::setUp();
    $this->installConfig(['search_api', 'system']);
    $this->installSchema('search_api', ['search_api_item']);
    $this->installEntitySchema('file');
    $this->installEntitySchema('media');
    $this->installEntitySchema('user');
    $this->installEntitySchema('search_api_task');
    // Create a collection, this also creates a search API index and puts all
    // items in it. Do not save it yet, though because saving triggers GraphQL
    // queries and the GraphQL responses need the collection id, so collection
    // create comes first, then Guzzle response setup then collection save.
    $this->collection = $this->container->get('entity_type.manager')->getStorage('pantheon_content_publisher_coll')->create([
      'id' => $this->randomMachineName(),
      'label' => $this->randomString(),
      'token' => $this->randomMachineName(),
      'url' => $this->randomMachineName(),
      'search_api_server' => 'default_server',
    ]);
    // Store the replies for every GraphQL query.
    foreach (array_keys(static::QUERIES) as $method) {
      $this->setGuzzleResponse($method);
    }
    // Then create the mock object.
    $mock = $this->getMockBuilder(Client::class)
      ->disableOriginalConstructor()
      ->onlyMethods(['post'])
      ->getMock();
    $mock->method('post')->willReturnCallback(fn ($uri, array $options) => new Response(200, [], $this->storage[json_decode($options['body'])->query]));
    $this->container->set('http_client', $mock);
    // Finally, save the collection.
    $this->collection->save();
  }

  public function testSearchAPIIndex() {
    // Creating the collection created a batch, let's run it.
    $batch = &batch_get();
    $batch['progressive'] = FALSE;
    batch_process();
    $indexes = Index::loadMultiple();
    $this->assertCount(1, $indexes);
    $index = reset($indexes);
    $this->assertSame($this->collection->id(), $index->id());
    $this->assertSame(['abooleanmeta', 'adatemeta', 'alistmeta', 'atextareameta', 'atextmeta', 'content'], array_keys($index->getFields()));
    $this->assertSame(1, $index->getTrackerInstance()->getTotalItemsCount());
    $this->assertSame(0, $index->getTrackerInstance()->getRemainingItemsCount());
    $this->assertSame('textarea test contents', $this->getSearchAPIvalue('atextareameta'));
    $newValue = $this->updateArticleInPantheon();
    // Notify the system the value has been updated.
    $webhook = $this->container->get('controller_resolver')->getControllerFromDefinition(PantheonContentPublisherController::class . '::webhook');
    $content = [
      'event' => 'article.update',
      'payload' => ['articleId' => self::ARTICLE_ID],
    ];
    $request = Request::create('/webhook', content: json_encode($content));
    $webhook($request);
    $this->assertSame($newValue, $this->getSearchAPIvalue('atextareameta'));
  }

  public function testCollectionUpdate(): void {
    // Setup created a collection, let's check it's correct.
    $storages = FieldStorageConfig::loadMultiple();
    $this->assertSame($storages['pantheon_content_publisher.abooleanmeta']->getType(), 'boolean');
    $this->assertSame($storages['pantheon_content_publisher.adatemeta']->getType(), 'timestamp');
    $this->assertSame($storages['pantheon_content_publisher.alistmeta']->getType(), 'list_string');
    $this->assertSame(options_allowed_values($storages['pantheon_content_publisher.alistmeta']), [
      'Option a' => 'Option a',
      'Option b' => 'Option b',
      'Option c' => 'Option c'
    ]);
    $this->assertSame($storages['pantheon_content_publisher.atextmeta']->getType(), 'string');
    $this->assertSame($storages['pantheon_content_publisher.atextareameta']->getType(), 'string_long');
    // Remove Option b from the metadata.
    $this->setGuzzleResponse('metadata', ['metadataFields', 'A list meta', 'options', 1]);
    // Update the collection.
    $this->collection->save();
    // Verify the list field changed.
    $storages = FieldStorageConfig::loadMultiple();
    $this->assertSame(options_allowed_values($storages['pantheon_content_publisher.alistmeta']), [
      'Option a' => 'Option a',
      'Option c' => 'Option c'
    ]);
    // Remove the list field.
    $this->setGuzzleResponse('metadata', ['metadataFields', 'A list meta']);
    // Update the collection.
    $this->collection->save();
    // Verify it's gone.
    $storages = FieldStorageConfig::loadMultiple();
    $this->assertArrayNotHasKey('pantheon_content_publisher.alistmeta', $storages);
  }

  public function testStorageDoLoadMultiple(): void {
    $storage = $this->container->get('entity_type.manager')->getStorage('pantheon_content_publisher');
    $entity_id = PantheonContentPublisherStorage::getEntityId($this->collection->id(), self::ARTICLE_ID);
    $pantheonContentPublisher = $storage->load($entity_id);
    $this->assertSame('textarea test contents', $pantheonContentPublisher->atextareameta->value);
    $this->assertSame('test title', $pantheonContentPublisher->label());
    $this->assertSame(sprintf('<a href="/pantheon-content-publisher/%s" hreflang="und">test title</a>', $entity_id), $pantheonContentPublisher->toLink()->toString()->getGeneratedLink());
    // Update article in Pantheon
    $newValue = $this->updateArticleInPantheon();
    $pantheonContentPublisher = $storage->loadUnchanged($entity_id);
    $this->assertSame($newValue, $pantheonContentPublisher->atextareameta->value);
  }

  public function testListBuilder() {
    // The core list builder uses entity query. If it gets overridden for
    // pagination purposes then a separate entity query test needs to be
    // added but until then, for basic functionality this test is enough.
    $build = $this->container->get('entity_type.manager')
      ->getListBuilder('pantheon_content_publisher')
      ->render();
    $html = (string) $this->container->get('renderer')
      ->renderInIsolation($build);
    $entity_id = PantheonContentPublisherStorage::getEntityId($this->collection->id(), self::ARTICLE_ID);
    $this->assertStringContainsString(sprintf('<td><a href="/pantheon-content-publisher/%s" hreflang="und">test title</a></td>', $entity_id), $html);
  }

  /**
   * Updates the "A textarea meta" field in Pantheon.
   *
   * @return string
   *   The new value of the field.
   */
  protected function updateArticleInPantheon(): string {
    $newValue = $this->randomString();
    $this->setGuzzleResponse('getArticle', ['metadata', 'A textarea meta'], $newValue);
    return $newValue;
  }

  /**
   * Sets a Guzzle response.
   *
   * @param string $method
   *   The method on this class, the only valid methods are the keys of
   *   the ::QUERIES constant. The return value of this method -- optionally
   *   changed as dictated by $parents and $newValue -- is stored as the Guzzle
   *   response to the query specified in the ::QUERIES constant for this
   *   method.
   * @param array $parents
   *   The parents to be passed to a NestedArray method.
   * @param string $newValue
   *   When empty then unset the element specified by $parents. When not empty
   *   then set the element specified by $parents to this value.
   */
  protected function setGuzzleResponse(string $method, array $parents = [], string $newValue = ''): void {
    $query = static::QUERIES[$method];
    $type = static::QUERY_TYPES[$method] ?? 'articlesv3';
    if (str_contains($query, '%')) {
      $query = sprintf($query, $type === 'site' ? $this->collection->id() : static::ARTICLE_ID);
    }
    $data = $this->$method();
    if ($parents) {
      if ($newValue) {
        NestedArray::setValue($data, $parents, $newValue);
      }
      else {
        NestedArray::unsetValue($data, $parents);
      }
    }
    $this->storage[$query] = json_encode(['data' => [$type => $data]]);
  }

  /**
   * Retrieve the value Search API stores for a given field.
   *
   * This is a very stupid helper, only usable if there is only one document
   * in search API.
   *
   * @param string $field
   *   Name of the field.
   *
   * @return string
   *   The search API stored value.
   */
  public function getSearchAPIvalue(string $field): string {
    return $this->container->get('database')
      ->select(sprintf("search_api_db_%s_%s", $this->collection->id(), $field), 's')
      ->fields('s', ['value'])
      ->execute()
      ->fetchField();
  }

  protected function metadata(): array {
    return ['metadataFields' => [
      'A boolean meta' => [
        'title' => 'A boolean meta',
        'type' => 'boolean',
      ],
      'A date meta' => [
        'title' => 'A date meta',
        'type' => 'date',
      ],
      'A file meta' => [
        'title' => 'A file meta',
        'type' => 'file',
      ],
      'A list meta' => [
        'options' => [
          0 => 'Option a',
          1 => 'Option b',
          2 => 'Option c',
        ],
        'title' => 'A list meta',
        'type' => 'list',
      ],
      'A text meta' => [
        'title' => 'A text meta',
        'type' => 'text',
      ],
      'A textarea meta' => [
        'title' => 'A textarea meta',
        'type' => 'textarea',
      ],
    ]];
  }

  protected function getArticleIds(): array {
    return [
      'articles' => [
        ['id' => self::ARTICLE_ID],
      ],
      "pageInfo" => [
        "totalCount" => 1,
        'nextCursor' => 'next cursor',
      ],
    ];
  }

  protected function getPage2ArticleIds(): array {
    $articleIds = $this->getArticleIds();
    $articleIds['articles'] = [];
    return $articleIds;
  }

  protected function getArticle() {
    return [
      'metadata' => [
        'A boolean meta' => TRUE,
        'A date meta' => ['msSinceEpoch' => 1741385249172],
        'A file meta' => 'https://cdn.prod.pcc.pantheon.io/pcc-prod-user-uploads/dfa6f309-537c-4ffe-bbdf-4a40a6e70a61',
        'A list meta' => 'Option c',
        'A text meta' => 'Plain text field test contents',
        'A textarea meta' => 'textarea test contents',
        'description' => 'A random description',
      ],
      'content' => 'test content',
      'title' => 'test title',
    ];
  }

  protected function getArticles() {
    return ['articles' => [[
      'id' => self::ARTICLE_ID
    ] + $this->getArticle()]];
  }

}

